site_name: A.R.M Project Docs
site_url: null
repo_url: https://github.com/SteveBunt/arm-documentation
repo_name: github
site_description: Development documentation for the Automatic Ripping Machine project
remote_branch: gh-pages
remote_name: origin
nav:
  - Overview: index.md
  - v3 Scope: v3scope.md
  - Roadmap: roadmap.md
  - Architecture: architecture.md
  #- Development: development.md
  #- Contributing: contributing.md
  #- Changelog: changelog.md
theme:
  name: readthedocs
  locale: en
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: primary
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  hljs_languages:
    - bash
    - python
    - yaml
    - json
    - ini
    - markdown
#  shortcuts:
  navigation_depth: 4
  docs_dir: dev_docs
  site_dir: site
